#!/usr/bin/python3

'''
this is a specific wrapper written for debuild since it does not have "warnings as errors"
and produces copious amounts of junk as output.
'''

import sys # for argv, exit
import templar.capture_all # for capture_all

seen_error=False
for line in templar.capture_all.capture_all(sys.argv[1:]):
	do_print=False
	line=line.decode()
	if line.find('warning')!=1:
		do_print=True
		seen_error=True
	if line.startswith('W: '):
		do_print=True
		seen_error=True
	if do_print:
		print(line, end='')
if seen_error:
	sys.exit(1)
