#!/usr/bin/python3

'''
this is a specific wrapper written for debuild since it does not have "warnings as errors"
and produces copious amounts of junk as output.
'''

import sys # for argv, exit
import templar.capture_all # for capture_all

seen_error=False
do_errors=False
do_always_print=False
for line in templar.capture_all.capture_all(sys.argv[1:]):
	do_print=False
	if line.find('warning')!=-1:
		do_print=True
		seen_error=True
	if line.startswith('W: '):
		do_print=True
		seen_error=True
	if do_print or do_always_print:
		print('got bad line [{0}]'.format(line.rstrip()))
if seen_error and do_errors:
	sys.exit(1)
