##############
# parameters #
##############
# do you want to show the commands executed ?
DO_MKDBG?=0

########
# code #
########
# silent stuff
ifeq ($(DO_MKDBG),1)
TEMPLAR_Q:=
# we are not silent in this branch
else # DO_MKDBG
TEMPLAR_Q:=@
#.SILENT:
endif # DO_MKDBG
