include /usr/share/templar/make/Makefile.templar
include /usr/share/templar/make/Makefile.package_build
include /usr/share/templar/make/Makefile.toplevel
include /usr/share/templar/make/Makefile.check_py
include /usr/share/templar/make/Makefile.debug
