# checks

.PHONY: check_py_main
check_py_main:
	$(info doing [$@])
	$(Q)make_helper wrapper-ok git grep __main -- "*.py"
.PHONY: check_py_semicol
check_py_semicol:
	$(info doing [$@])
	$(Q)make_helper wrapper-ok git grep ";$$" -- "*.py"

.PHONY: check_py_all
check_py_all: check_py_main check_py_semicol
	$(info doing [$@])
