.DEFAULT_GOAL=all
.PHONY: all
all: $(ALL)
	@true
#this is to avoid 'make: Nothing to be done for 'all'.' message
#$(info doing [$@])
#@true

.PHONY: clean
clean:
	$(info doing [$@])
	$(TEMPLAR_Q)git clean -ffqxd

.PHONY: debug
debug:
	$(info doing [$@])
	$(info ALL is $(ALL))
