.DEFAULT_GOAL=all
.PHONY: all
all: $(ALL)
	$(info doing [$@])
#this is to avoid 'make: Nothing to be done for 'all'.' message
#@true

.PHONY: clean
clean:
	$(info doing [$@])
	$(Q)git clean -xdf > /dev/null

.PHONY: debug
debug:
	$(info doing [$@])
	$(info ALL is $(ALL))
