.DEFAULT_GOAL=all
.PHONY: all
all: tools.stamp $(ALL)
	@true
#this is to avoid 'make: Nothing to be done for 'all'.' message
#$(info doing [$@])
#@true

tools.stamp: templardefs/deps.py
	$(info doing [$@])
	@templar_cmd install_deps
	@make_helper touch-mkdir $@

.PHONY: clean
clean:
	$(info doing [$@])
	$(TEMPLAR_Q)git clean -ffqxd

.PHONY: debug
debug:
	$(info doing [$@])
	$(info ALL is $(ALL))
